sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
- 3.7-dev
install:
- pip install wheel codecov coverage tox-travis
- python setup.py bdist_wheel
- pip install ./dist/pyTMCL-*.whl
script: tox --installpkg ./dist/pyTMCL-*.whl
after_success: coverage combine && codecov
stages:
- test
- name: deploy
  if: tag IS present
jobs:
  fast_finish: true
  include:
  - stage: deploy
    python: 3.6
    install: true
    script: true
    after_success: true
    deploy:
      provider: pypi
      user: lukecodewalker
      password:
        secure: 3QxWOJDKsdiI47k3OJy+t8WN18ruyE62xnZ+DBfg8GfSFl2Z8unDLnKsnInga47OVfrZ0eiKu3RZ26wh/FhILywfKUXX5FCzU544vh9LC4b5Nv8qZoiu+FY39/kR3pQkzWS50vGj6AV1hCIEIzx1jfeXBo8Jt7FPo5tXZenvpQF+Wsf4Xu7L7Ws0CdbwVehntegrdf/iyhFIJd+41pChAE7mWyRoL1Bqhkg5rrqA6Ns89UxstbabYPUhwW/ljSUHfSDXRdegZyjJ8mMifUdvIOeLRoZubKV7bq61NWR+99UcUwPCpK2Squ/ayKxWpAk2+GiO8/uIXhphtVoiizsgKuoTpZOUEUt0ivtOmHmw+wQtK0Cu0R1KCojCQFkzP++EpSK9p0ZC+CpdFr3eRfCfO9hZxKorcNxep8i6LSN3OXrhrvJYhxM9jKr8cY+VOW8S9/pJ5TOabQV1JoMlKDCUpgAw99FL81dYInoo5s9N3w8v/hQBJMPc3WXnVF9Vc7ShmrTulFdvlBATFmdL9Rh8GGqL4TFPY8opSx17cX5gKhLup5gDAaS9jhTO958AwopjlZVT4XcK4tgXSyAET6QIfaVIKD9N9Us4xMGnbC71CHsY5zDL66WOm+iHW/MTg6vBPszdxbYX4PUdApYejkdAqXvGPCAw0OCSgb2t6c5vZnM=
      on:
        tags: true
