sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
- 3.7-dev
install:
- pip install wheel codecov coverage tox-travis
- python setup.py bdist_wheel
- pip install ./dist/pyTMCL-*.whl
script: tox --installpkg ./dist/pyTMCL-*.whl
after_success: coverage combine && codecov
stages:
- test
- name: deploy
  if: tag IS present
jobs:
  fast_finish: true
  include:
  - stage: deploy
    python: 3.6
    install: true
    script: true
    after_success: true
    deploy:
      provider: pypi
      user: lukecodewalker
      password:
        secure: pjFOvos4EPRXyJK/kmetnRPd8EShjPaAtdleOlSgt1l9K8dtGygyKNGWURP6vFWfSKIbeDJPLsNiFZemFKdCYV415+QK040CXj+QGh3TGnw/oVi+PAXZjp0nwdtWC39BPXtv6NTdLK16qhk3lMpOqlIbh47I16Iuw50odkE48arBLdYB/oAJb2xbwPGHjueTSKIwhUVJhLzhD/PLiWg3mzYssTcMNn+ehYWUbI1zPVMi5jrfj1bkiHXDFz/4sDzMQVOjTpshLXa5/zPlNj/tNuepzLjIIS0JBUHjHuDF0nuHzclEjOIFP5lncbAcjBFzm9u3/vL2ao2xoUrpXwgpBSQaYyrz1l/0WYEHVPlFN6XWY6BJXvxxmDzr2oDMfnX9RbjIUpxUowHSKZH6NE0sPMbPxpnBEint/uJHIGUxjbthgLaO/Dt5b/ba/wuCe15/kBezCNPM+XxRb4ucHZ5Wkk20t5i1w3uMU0WAvRP34yJ6QxNoejSye2YMrRwbCZyqi0EE++hy+lzumMg4C87IM6Vod+OwyXsIHuDVQ/uCc+lMUdd7n6xJ+bmH97kMy+Cn5OpKVXgHMrlxSIXkmfwTEQhRLUrXRKoIG2TheeBxZWKqcbxc3YdlX2v0whYPBBk6d0QeAnW8U15tk7SMYC4EteIJdncIeqrWy1tGWE53wC4=
      on:
        tags: true
