sudo: false
language: python
python:
 - "2.6"
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "pypy"
 - "pypy3"
 - "3.7-dev"

install:
 - pip install wheel codecov coverage
 - python setup.py bdist_wheel
 - pip install ./dist/pyTMCL-*.whl
script: tox --installpkg ./dist/pyTMCL-*.whl
after_success: coverage combine && codecov

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=docs
  - python: 3.6
    env: TOXENV=desc
  - stage: deploy
    python: 3.6
    install: true
    script: true
    after_success: true
    deploy:
      provider: pypi
			user: lukecodewalker
			password:
				secure: BFYQvM9kSHPVwUq8Q49/VdkY/istxHn/J0waULwLJQDJoEy/a20iu2k+JPoog2zgorwvpVcbqpamVAjTQ4S3GfT5lsegTr1qhsD4bJfOm/Phe8GV+wWxEDBg6EzJUOxZyeMeVU2/b9y4zPGq5x9utJ9KYrm7S8KlVQfNsKl0Pi7hh9XST1P6K2h7aiSjPZsytDjw7YjTWiJgZ3lHzJwvUrYuRkiNb+VPqTvEnUdm116OzpAbYJXAMTM3XocyL6lPpdVk7I1zk/KBL847MMSrBWE7hT72MvAhOSCzksytcCBIphCGBp/KPYliSGkTc3Czl5Z3JN/aF+F5cQqnxO7pglO45+X4yTGU/VfeCE/YLDi8DUundxAo/tifBiTVV+sp6+5wjvOHlGxJ+qSAjECadQdY5mUFPjSwxfZglzpzVuO2+DMC3PwiUIaccnxPBiKHff0KRyBRRcETDCeCQ8rhtdIdjdrFoI0KEJRwALmXvUmI0Ho8MBQwGnXr7HKxMCvs0Qyd++K3z2gCKw5UOWoDqjwIidhVBQr1W1106wu3K8qsRup68Rt+nGpdsbp5hjeOTrB8Z+79StycjW+TnmT5BnNm+HbbOK4MRooZUFIF2aG9BwpkBh3nvZTYvIUC3nhWmsJ84REIjpJX4OvYNlUCSqk7G70V3oaIZ3YpJJ5LgHY=
			on:
		    tags: true
